### ISSUE TITLE
errors when color scale has only 1 value

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-geomap#12] opened 2017-09-19 17:59 UTC
### Expected Behavior
Expectation: the map will load, and there will be one value colored in accordance with the maximal value of the specified color scale.

### Current Behavior
The map shape is filled in black (not part of color scale) and the "powered by d3plus" text doesn't disappear.

### Steps to Reproduce (for bugs)
1. https://jsfiddle.net/jonathan_dw/ocngp6mr/5/

![screen shot 2017-09-19 at 1 59 05 pm](https://user-images.githubusercontent.com/87581/30607371-b8b6bbca-9d42-11e7-9835-48182e8f6f4a.png)

**Comment by davelandry** [comment] 2017-09-19 18:25
Duplicate of #7

**Closed as completed by davelandry** 2017-09-19 18:25 UTC
